#include <ranges>
#include <algorithm>
#include <vector>
#include <array>
#include <string_view>
#include <optional>

#include "part2.h"
#include "utils.h"

namespace
{
    using namespace std::string_view_literals;

    constinit std::array vol_1 = std::to_array<volume_definition>({
{ volume::P2V1, "toc.ncx"sv, "application/x-dtbncx+xml"sv, std::nullopt, false },
{ volume::P2V1, "Styles/stylesheet.css"sv, "text/css"sv, std::nullopt, false },
{ volume::FB2, "Styles/stylesheet.css"sv, "text/css"sv, std::nullopt, false },
{ volume::P2V1, "Images/Cover.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V1, "Images/Insert1.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V1, "Images/Insert2.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V1, "Images/Insert3.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V1, "Images/Insert4.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V1, "Images/Insert5.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V1, "Images/Insert6.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V1, "Images/Insert7.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V1, "Images/Insert8.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V1, "Images/Insert9.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V1, "Images/FrontMatter1.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V1, "Images/Characters2.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V1, "Images/Characters1.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V1, "Images/Bonus1.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V1, "Images/FrontMatter2.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V1, "Images/Bonus2.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V1, "Images/jnovelclubCMYK.png"sv, "image/png"sv, std::nullopt, false },
{ volume::P2V1, "Text/cover.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Cover"sv), true },
{ volume::P2V1, "Text/frontmatter1.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Color Illustrations"sv), true },
{ volume::P2V1, "Text/frontmatter2.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V1, "Text/characters1.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Characters"sv), true },
{ volume::P2V1, "Text/characters2.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V1, "Text/toc.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V1, "Text/prologue.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Prologue"sv), true },
{ volume::P2V1, "Text/chapter01.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Attendants and the Fealty Ceremony"sv), true },
{ volume::P2V1, "Text/insert1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V1, "Text/chapter01_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V1, "Text/chapter02.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("A Shrine Maiden’s Job"sv), true },
{ volume::P2V1, "Text/chapter03.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Not Like the Other Blue Robes"sv), true },
{ volume::P2V1, "Text/chapter04.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Benno’s Meeting With the High Priest"sv), true },
{ volume::P2V1, "Text/chapter05.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("The Meeting Begins"sv), true },
{ volume::P2V1, "Text/insert2.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V1, "Text/chapter05_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
//{ volume::MP2V1, "xhtml/p-185.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Story: Fran and the Commoner Apprentice Blue Shrine Maiden"sv), true },
{ volume::MP2V1, "xhtml/p-186.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Story: Fran and the Commoner Apprentice Blue Shrine Maiden"sv), true },
{ volume::MP2V1, "xhtml/p-187.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::MP2V1, "xhtml/p-188.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::MP2V1, "xhtml/p-189.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::MP2V1, "xhtml/p-190.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::MP2V1, "xhtml/p-191.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::MP2V1, "xhtml/p-192.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::MP2V1, "xhtml/p-193.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::MP2V1, "xhtml/p-194.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::MP2V1, "xhtml/p-195.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
//{ volume::MP2V1, "image/i-185.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V1, "image/i-186.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V1, "image/i-187.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V1, "image/i-188.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V1, "image/i-189.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V1, "image/i-190.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V1, "image/i-191.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V1, "image/i-192.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V1, "image/i-193.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V1, "image/i-194.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V1, "image/i-195.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V1, "style/fixed-layout.css"sv, "text/css"sv, std::nullopt, false },
{ volume::P2V1, "Text/chapter06.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Buying Secondhand Clothes"sv), true },
{ volume::P2V1, "Text/extra1.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("A Place Still Far From Here"sv), true },
{ volume::P2V1, "Text/chapter07.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("The Animosity of Lutz and Gil"sv), true },
{ volume::P2V1, "Text/insert3.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V1, "Text/chapter07_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V1, "Text/chapter08.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("What They Deserve"sv), true },
{ volume::P2V1, "Text/chapter09.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("First Time Outside"sv), true },
{ volume::P2V1, "Text/chapter10.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Training the Chefs"sv), true },
{ volume::P2V1, "Text/insert4.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V1, "Text/chapter10_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V1, "Text/chapter11.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Delia’s Job"sv), true },
{ volume::P2V1, "Text/chapter12.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("The Reality of the Orphanage"sv), true },
{ volume::P2V1, "Text/chapter13.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Discussion With the High Priest and My Resolve"sv), true },
//{ volume::MP2V2, "xhtml/p-169.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Story: The Other Side of the Orphanage Incident"sv), true },
{ volume::MP2V2, "xhtml/p-170.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Story: The Other Side of the Orphanage Incident"sv), true },
{ volume::MP2V2, "xhtml/p-171.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::MP2V2, "xhtml/p-172.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::MP2V2, "xhtml/p-173.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::MP2V2, "xhtml/p-174.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::MP2V2, "xhtml/p-175.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::MP2V2, "xhtml/p-176.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::MP2V2, "xhtml/p-177.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
//{ volume::MP2V2, "image/i-169.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V2, "image/i-170.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V2, "image/i-171.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V2, "image/i-172.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V2, "image/i-173.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V2, "image/i-174.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V2, "image/i-175.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V2, "image/i-176.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V2, "image/i-177.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V2, "style/fixed-layout.css"sv, "text/css"sv, std::nullopt, false },
{ volume::P2V1, "Text/chapter14.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Secret Talk With the High Priest"sv), true },
{ volume::P2V1, "Text/insert5.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V1, "Text/chapter14_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::MP2V2, "xhtml/p-161.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Extra: Sister Myne and Me"sv), true },
{ volume::MP2V2, "xhtml/p-162.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::MP2V2, "xhtml/p-163.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::MP2V2, "xhtml/p-164.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::MP2V2, "xhtml/p-165.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::MP2V2, "xhtml/p-166.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::MP2V2, "xhtml/p-167.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::MP2V2, "xhtml/p-168.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::MP2V2, "image/i-161.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V2, "image/i-162.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V2, "image/i-163.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V2, "image/i-164.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V2, "image/i-165.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V2, "image/i-166.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V2, "image/i-167.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V2, "image/i-168.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V1, "Text/chapter15.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Cleaning Up the Orphanage"sv), true },
{ volume::P2V1, "Text/chapter16.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Ideas for New Products"sv), true },
{ volume::P2V1, "Text/insert6.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V1, "Text/chapter16_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V1, "Text/extra2.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("An Attendant’s Self-Awareness"sv), true },
{ volume::P2V1, "Text/chapter17.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Diptychs and Cards"sv), true },
{ volume::P2V1, "Text/chapter18.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Preparing for the Star Festival"sv), true },
//{ volume::MP2V3, "xhtml/p-161.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Extra: Ordering Ceremonial Robes"sv), true },
//{ volume::MP2V3, "xhtml/p-162.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::MP2V3, "xhtml/p-163.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Extra: Ordering Ceremonial Robes"sv), true },
{ volume::MP2V3, "xhtml/p-164.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::MP2V3, "xhtml/p-165.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::MP2V3, "xhtml/p-166.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::MP2V3, "xhtml/p-167.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::MP2V3, "xhtml/p-168.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::MP2V3, "xhtml/p-169.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::MP2V3, "xhtml/p-170.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
//{ volume::MP2V3, "image/i-161.jpg"sv, "image/jpeg"sv, std::nullopt, false },
//{ volume::MP2V3, "image/i-162.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V3, "image/i-163.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V3, "image/i-164.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V3, "image/i-165.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V3, "image/i-166.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V3, "image/i-167.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V3, "image/i-168.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V3, "image/i-169.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V3, "image/i-170.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V3, "style/fixed-layout.css"sv, "text/css"sv, std::nullopt, false },
{ volume::P2V1, "Text/chapter19.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("The Star Festival"sv), true },
{ volume::P2V1, "Text/insert7.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V1, "Text/chapter19_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
//{ volume::MP2V3, "xhtml/p-171.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Story: Gathering Taues"sv), true },
{ volume::MP2V3, "xhtml/p-172.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Story: Gathering Taues"sv), true },
{ volume::MP2V3, "xhtml/p-173.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::MP2V3, "xhtml/p-174.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::MP2V3, "xhtml/p-175.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::MP2V3, "xhtml/p-176.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::MP2V3, "xhtml/p-177.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::MP2V3, "xhtml/p-178.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::MP2V3, "xhtml/p-179.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
//{ volume::MP2V3, "image/i-171.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V3, "image/i-172.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V3, "image/i-173.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V3, "image/i-174.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V3, "image/i-175.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V3, "image/i-176.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V3, "image/i-177.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V3, "image/i-178.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V3, "image/i-179.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V1, "Text/chapter20.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("After the Festival"sv), true },
{ volume::P2V1, "Text/chapter21.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Lutz’s Path Through Life"sv), true },
{ volume::P2V1, "Text/chapter22.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Lutz Running Away from Home"sv), true },
{ volume::P2V1, "Text/insert8.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V1, "Text/chapter22_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
//{ volume::MP2V4, "xhtml/p-157.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Story: This Thing Called Family"sv), true },
{ volume::MP2V4, "xhtml/p-158.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Story: This Thing Called Family"sv), true },
{ volume::MP2V4, "xhtml/p-159.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::MP2V4, "xhtml/p-160.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::MP2V4, "xhtml/p-161.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::MP2V4, "xhtml/p-162.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::MP2V4, "xhtml/p-163.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::MP2V4, "xhtml/p-164.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::MP2V4, "xhtml/p-165.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::MP2V4, "xhtml/p-166.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
//{ volume::MP2V4, "xhtml/p-167.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
//{ volume::MP2V4, "image/i-157.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V4, "image/i-158.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V4, "image/i-159.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V4, "image/i-160.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V4, "image/i-161.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V4, "image/i-162.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V4, "image/i-163.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V4, "image/i-164.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V4, "image/i-165.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V4, "image/i-166.jpg"sv, "image/jpeg"sv, std::nullopt, false },
//{ volume::MP2V4, "image/i-167.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V4, "style/fixed-layout.css"sv, "text/css"sv, std::nullopt, false },
{ volume::P2V1, "Text/chapter23.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("The High Priest’s Letter of Invitation"sv), true },
{ volume::P2V1, "Text/chapter24.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Family Meeting at the Temple"sv), true },
{ volume::P2V1, "Text/insert9.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V1, "Text/chapter24_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V1, "Text/epilogue.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Epilogue"sv), true },
{ volume::FB2, "Text/side2.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("I’m Not Givin’ Ya My Daughter!"sv), true },
{ volume::P2V1, "Text/afterword.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Afterword"sv), true },
{ volume::P2V1, "Text/bonus1.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Bonus High Resolution Illustrations"sv), true },
{ volume::P2V1, "Text/bonus2.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V1, "Text/signup.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("About J-Novel Club"sv), true },
{ volume::P2V1, "Text/copyright.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Copyright"sv), true },
        });


constinit std::array vol_2 = std::to_array<volume_definition>({
{ volume::P2V2, "toc.ncx"sv, "application/x-dtbncx+xml"sv, std::nullopt, false },
{ volume::P2V2, "Styles/stylesheet.css"sv, "text/css"sv, std::nullopt, false },
{ volume::FB2, "Styles/stylesheet.css"sv, "text/css"sv, std::nullopt, false },
{ volume::P2V2, "Images/Cover.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V2, "Images/Insert1.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V2, "Images/Insert2.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V2, "Images/Insert3.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V2, "Images/Insert4.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V2, "Images/Insert5.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V2, "Images/Insert6.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V2, "Images/Insert7.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V2, "Images/Insert8.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V2, "Images/Insert9.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V2, "Images/FrontMatter1.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V2, "Images/FrontMatter2.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V2, "Images/Bonus1.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V2, "Images/Bonus2.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V2, "Images/Characters1.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V2, "Images/Characters2.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V2, "Images/jnovelclubCMYK.png"sv, "image/png"sv, std::nullopt, false },
{ volume::P2V2, "Text/cover.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Cover"sv), true },
{ volume::P2V2, "Text/frontmatter1.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Color Illustrations"sv), true },
{ volume::P2V2, "Text/frontmatter2.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V2, "Text/characters1.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Characters"sv), true },
{ volume::P2V2, "Text/characters2.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V2, "Text/toc.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V2, "Text/prologue.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Prologue"sv), true },
{ volume::P2V2, "Text/chapter01.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("One Wilma, Please"sv), true },
{ volume::P2V2, "Text/insert1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V2, "Text/chapter01_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V2, "Text/chapter02.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Rosina and Harspiels"sv), true },
{ volume::P2V2, "Text/chapter03.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("An Attendant’s Job"sv), true },
{ volume::P2V2, "Text/extra1.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("The Attendant of an Apprentice Blue Shrine Maiden"sv), true },
{ volume::P2V2, "Text/insert9.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V2, "Text/extra1_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V2, "Text/chapter04.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("The Italian Restaurant’s Interior Decoration"sv), true },
{ volume::P2V2, "Text/insert2.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V2, "Text/chapter04_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V2, "Text/chapter05.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("How to Run a Restaurant"sv), true },
{ volume::P2V2, "Text/chapter06.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("The Significance of Going Outside"sv), true },
{ volume::P2V2, "Text/chapter07.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Preparing to Make Ink"sv), true },
{ volume::P2V2, "Text/chapter08.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Black Oil Paint"sv), true },
{ volume::P2V2, "Text/chapter09.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Making Picture Books with Woodblock Printing"sv), true },
{ volume::P2V2, "Text/chapter10.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Black-and-White Picture Books"sv), true },
//{ volume::MP2V5, "xhtml/p-169.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Story: Preparing for the Baby"sv), true },
{ volume::MP2V5, "xhtml/p-170.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Story: Preparing for the Baby"sv), true },
{ volume::MP2V5, "xhtml/p-171.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::MP2V5, "xhtml/p-172.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::MP2V5, "xhtml/p-173.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::MP2V5, "xhtml/p-174.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::MP2V5, "xhtml/p-175.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::MP2V5, "xhtml/p-176.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::MP2V5, "xhtml/p-177.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::MP2V5, "xhtml/p-178.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
//{ volume::MP2V5, "xhtml/p-179.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
//{ volume::MP2V5, "image/i-169.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V5, "image/i-170.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V5, "image/i-171.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V5, "image/i-172.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V5, "image/i-173.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V5, "image/i-174.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V5, "image/i-175.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V5, "image/i-176.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V5, "image/i-177.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V5, "image/i-178.jpg"sv, "image/jpeg"sv, std::nullopt, false },
//{ volume::MP2V5, "image/i-179.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::MP2V5, "style/fixed-layout.css"sv, "text/css"sv, std::nullopt, false },
{ volume::P2V2, "Text/chapter11.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Preparing for the Children’s Bible"sv), true },
{ volume::P2V2, "Text/insert3.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V2, "Text/chapter11_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V2, "Text/chapter12.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Binding Children’s Bibles"sv), true },
{ volume::P2V2, "Text/insert4.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V2, "Text/chapter12_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V2, "Text/chapter13.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Missing the Harvest Festival"sv), true },
{ volume::P2V2, "Text/chapter14.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("The Myne Decimal System"sv), true },
{ volume::FB2, "Text/side3.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("My Handful of a Little Sister"sv), true },
{ volume::P2V2, "Text/chapter15.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("A Book for Benno and First Fitting"sv), true },
{ volume::P2V2, "Text/chapter16.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Cinderella and a Book for the High Priest"sv), true },
{ volume::P2V2, "Text/chapter17.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("A Discussion About Winter Preparations"sv), true },
{ volume::P2V2, "Text/chapter18.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Off to Buy Winter Clothes"sv), true },
{ volume::P2V2, "Text/insert5.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V2, "Text/chapter18_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::FB2, "Text/side4.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Studying Literature and Picture Books"sv), true },
{ volume::P2V2, "Text/chapter19.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Butchering and Absence"sv), true },
{ volume::P2V2, "Text/extra2.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Apprentice Chef in the Temple"sv), true },
{ volume::P2V2, "Text/chapter20.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("The End of Winter Preparations"sv), true },
{ volume::P2V2, "Text/chapter21.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Summons from the Knight’s Order"sv), true },
{ volume::P2V2, "Text/insert6.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V2, "Text/chapter21_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V2, "Text/chapter22.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Trombe Extermination"sv), true },
{ volume::P2V2, "Text/chapter23.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Rescue and Reprimand"sv), true },
{ volume::P2V2, "Text/chapter24.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("The Healing Ritual"sv), true },
{ volume::P2V2, "Text/insert7.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V2, "Text/chapter24_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V2, "Text/epilogue.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Epilogue"sv), true },
{ volume::P2V2, "Text/insert8.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V2, "Text/epilogue_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V2, "Text/afterword.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Afterword"sv), true },
{ volume::P2V2, "Text/bonus1.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Bonus High Resolution Illustrations"sv), true },
{ volume::P2V2, "Text/bonus2.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V2, "Text/signup.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("About J-Novel Club"sv), true },
{ volume::P2V2, "Text/copyright.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Copyright"sv), true },
        });


    constinit std::array vol_3 = std::to_array<volume_definition>({
{ volume::P2V3, "toc.ncx"sv, "application/x-dtbncx+xml"sv, std::nullopt, false },
{ volume::P2V3, "Styles/stylesheet.css"sv, "text/css"sv, std::nullopt, false },
{ volume::P2V4, "Styles/stylesheet.css"sv, "text/css"sv, std::nullopt, false },
{ volume::P2V3, "Images/jnovelclubCMYK.png"sv, "image/png"sv, std::nullopt, false },
{ volume::P2V3, "Images/Bonus1.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V3, "Images/Bonus2.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V3, "Images/Characters1.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V3, "Images/Characters2.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V3, "Images/Cover.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V3, "Images/FrontMatter1.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V3, "Images/FrontMatter2.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V3, "Images/Insert1.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V3, "Images/Insert2.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V3, "Images/Insert3.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V3, "Images/Insert4.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V3, "Images/Insert5.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V3, "Images/Insert6.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V3, "Images/Insert7.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V3, "Images/Insert8.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V3, "Images/Insert9.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V3, "Images/Map.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V3, "Text/cover.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Cover"sv), true },
{ volume::P2V3, "Text/frontmatter1.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Color Illustrations"sv), true },
{ volume::P2V3, "Text/frontmatter2.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V3, "Text/map.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Map of Ehrenfest Duchy"sv), true },
{ volume::P2V3, "Text/characters1.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Characters"sv), true },
{ volume::P2V3, "Text/characters2.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V3, "Text/toc.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V3, "Text/prologue.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Prologue"sv), true },
{ volume::P2V3, "Text/chapter01.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Printing Guild"sv), true },
{ volume::P2V3, "Text/chapter02.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Johann’s Task"sv), true },
{ volume::P2V3, "Text/insert1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V3, "Text/chapter02_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V3, "Text/chapter03.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("The Ink Guild and the Beginning of Winter"sv), true },
{ volume::P2V3, "Text/chapter04.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Winter Hibernation and Handiwork"sv), true },
{ volume::P2V3, "Text/chapter05.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Meeting of the Minds"sv), true },
{ volume::P2V3, "Text/chapter06.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Punishment for the Knight’s Order and My Future"sv), true },
{ volume::P2V3, "Text/insert2.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V3, "Text/chapter06_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V3, "Text/chapter07.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Daily Winter Life"sv), true },
{ volume::P2V3, "Text/chapter08.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("The Dedication Ritual"sv), true },
{ volume::P2V3, "Text/chapter09.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Rosina’s Coming of Age Ceremony"sv), true },
{ volume::P2V3, "Text/insert3.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V3, "Text/chapter10.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Rumtopf and Shoes"sv), true },
{ volume::P2V3, "Text/chapter11.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Completion of the Metal Letter Types"sv), true },
{ volume::P2V3, "Text/extra2.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("The Title of “Gutenberg”"sv), true },
{ volume::P2V3, "Text/insert9.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V3, "Text/extra2_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V3, "Text/chapter12.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Temple Stay Extended"sv), true },
{ volume::P2V3, "Text/insert4.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V3, "Text/chapter12_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V3, "Text/extra1.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Lunchtime in the Temple"sv), true },
{ volume::P2V3, "Text/chapter13.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Preparing for the Spring Prayer"sv), true },
{ volume::P2V3, "Text/insert5.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V3, "Text/chapter14.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Spring Prayer"sv), true },
{ volume::P2V3, "Text/chapter15.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("An After-Meal Invitation"sv), true },
{ volume::P2V3, "Text/chapter16.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Ambush"sv), true },
{ volume::P2V3, "Text/insert6.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V3, "Text/chapter16_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V3, "Text/chapter17.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("The Wild and Uncontrollable Blue Priest"sv), true },
{ volume::P2V3, "Text/chapter18.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Visit to the Orphanage and Workshop"sv), true },
{ volume::P2V3, "Text/insert7.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V3, "Text/chapter18_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V4, "Text/extra8.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Leon—Sylvester Undercover"sv), true },
{ volume::P2V3, "Text/chapter19.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Talking with the High Priest and Returning Home"sv), true },
{ volume::P2V3, "Text/chapter20.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("A New Member of the Family"sv), true },
{ volume::P2V3, "Text/insert8.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V3, "Text/chapter20_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V3, "Text/epilogue.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Epilogue"sv), true },
{ volume::P2V3, "Text/afterword.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Afterword"sv), true },
{ volume::P2V3, "Text/bonus1.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Bonus High Resolution Illustrations"sv), true },
{ volume::P2V3, "Text/bonus2.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V3, "Text/signup.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("About J-Novel Club"sv), true },
{ volume::P2V3, "Text/copyright.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Copyright"sv), true },
        });


constinit std::array vol_4 = std::to_array<volume_definition>({
{ volume::P2V4, "toc.ncx"sv, "application/x-dtbncx+xml"sv, std::nullopt, false },
{ volume::P2V4, "Styles/stylesheet.css"sv, "text/css"sv, std::nullopt, false },
{ volume::FB2, "Styles/stylesheet.css"sv, "text/css"sv, std::nullopt, false },
{ volume::FB1, "Styles/stylesheet.css"sv, "text/css"sv, std::nullopt, false },
{ volume::P2V4, "Images/jnovelclubCMYK.png"sv, "image/png"sv, std::nullopt, false },
{ volume::P2V4, "Images/Bonus1.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V4, "Images/Bonus2.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V4, "Images/Characters1.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V4, "Images/Characters2.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V4, "Images/Cover.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V4, "Images/FrontMatter1.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V4, "Images/FrontMatter2.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V4, "Images/Insert1.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V4, "Images/Insert2.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V4, "Images/Insert3.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V4, "Images/Insert4.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V4, "Images/Insert5.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V4, "Images/Insert6.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V4, "Images/Insert7.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V4, "Images/Insert8.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V4, "Images/Insert9.jpg"sv, "image/jpeg"sv, std::nullopt, false },

{ volume::P2V4, "Images/Manga1.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V4, "Images/Manga2.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V4, "Images/Map.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V4, "Text/cover.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Cover"sv), true },
{ volume::P2V4, "Text/frontmatter1.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Color Illustrations"sv), true },
{ volume::P2V4, "Text/frontmatter2.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V4, "Text/map.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Map of Ehrenfest Duchy"sv), true },
{ volume::P2V4, "Text/characters1.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Characters"sv), true },
{ volume::P2V4, "Text/characters2.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V4, "Text/toc.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V4, "Text/prologue.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Prologue"sv), true },
{ volume::P2V4, "Text/chapter1.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Caring for Kamil"sv), true },
{ volume::P2V4, "Text/chapter2.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("The Abandoned Child"sv), true },
{ volume::P2V4, "Text/insert1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V4, "Text/chapter2_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V4, "Text/chapter3.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("What to Do About Dirk"sv), true },
{ volume::P2V4, "Text/chapter4.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("The Ink Guild and Succession"sv), true },
{ volume::P2V4, "Text/chapter5.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Researching Color-Making"sv), true },
{ volume::P2V4, "Text/insert2.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V4, "Text/chapter5_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V4, "Text/chapter6.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Challenging Wax Stencils"sv), true },
{ volume::P2V4, "Text/extra7.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Josef—Beruf Certification"sv), true },
{ volume::P2V4, "Text/chapter7.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Delia’s Progress"sv), true },
{ volume::P2V4, "Text/chapter8.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Both Sides of the Story"sv), true },
{ volume::P2V4, "Text/chapter9.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("The Two Who Left"sv), true },
{ volume::P2V4, "Text/chapter10.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("The Shadow Falls"sv), true },
{ volume::P2V4, "Text/insert3.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V4, "Text/chapter10_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V4, "Text/chapter11.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("The Noble from Another Duchy"sv), true },
{ volume::P2V4, "Text/insert4.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V4, "Text/chapter11_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V4, "Text/chapter12.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("The Black Charm"sv), true },
{ volume::P2V4, "Text/insert5.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V4, "Text/chapter12_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V4, "Text/chapter13.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("The Source of Strife"sv), true },
{ volume::P2V4, "Text/insert6.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V4, "Text/chapter13_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V4, "Text/chapter14.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("The New Me"sv), true },
{ volume::P2V4, "Text/chapter15.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Ripped Apart"sv), true },
{ volume::P2V4, "Text/insert7.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V4, "Text/chapter15_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V4, "Text/extra2.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Sylvester—Cleaning up the Mess"sv), true },
{ volume::P2V4, "Text/extra1.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Freida—A Visit to the Noble’s Quarter"sv), true },
{ volume::P2V4, "Text/extra3.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Arno—Fran and I"sv), true },
{ volume::P2V4, "Text/extra4.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Benno—Maybe Lessen the Workload"sv), true },
{ volume::FB1, "Text/temple.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Temple Tour by Miya Kazuki"sv), true },
{ volume::FB1, "Text/24.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::FB1, "Text/temple_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::FB1, "Images/24.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P2V4, "Text/epilogue.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Epilogue"sv), true },
{ volume::P2V4, "Text/insert8.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V4, "Text/epilogue_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V4, "Text/extra5.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Fran—To Serve as the High Bishop’s Attendant"sv), true },
{ volume::P2V4, "Text/extra6.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Effa—Facing the Future"sv), true },
{ volume::P2V4, "Text/insert9.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V4, "Text/afterword.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Afterword"sv), true },
{ volume::P2V4, "Text/manga1.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Coming Out of Nowhere to Celebrate the Conclusion of Part 2, It’s the First Ever End of Volume Bonuses! by You Shiina"sv), true },
{ volume::P2V4, "Text/manga2.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V4, "Text/bonus1.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Bonus High Resolution Illustrations"sv), true },
{ volume::P2V4, "Text/bonus2.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P2V4, "Text/signup.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("About J-Novel Club"sv), true },
{ volume::P2V4, "Text/copyright.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Copyright"sv), true },
        });

    constexpr std::array _part_2_list = std::to_array<std::span<const volume_definition>>({
            std::span(vol_1), std::span(vol_2), std::span(vol_3), std::span(vol_4)
    });

    constexpr std::ranges::join_view _part_2_view {_part_2_list};

    const std::vector<volume_definition> _part_2 = utils::make_omnibus_def(_part_2_view, utils::calc_reservation(_part_2_list));
} // namespace

namespace part_2
{
    using namespace std::string_view_literals;

    std::span<const volume_definition>
    get_vol_1()
    {
        return std::span<const volume_definition>(vol_1);
    }

    std::span<const volume_definition>
    get_vol_2()
    {
        return std::span<const volume_definition>(vol_2);
    }

    std::span<const volume_definition>
    get_vol_3()
    {
        return std::span<const volume_definition>(vol_3);
    }

    std::span<const volume_definition>
    get_vol_4()
    {
        return std::span<const volume_definition>(vol_4);
    }

    std::span<const volume_definition>
    get_part_2()
    {
        return std::span<const volume_definition>(_part_2);
    }

    size_t
    get_reservation()
    {
        return _part_2.size();
    }
}
