#include <ranges>
#include <algorithm>
#include <vector>
#include <array>
#include <string_view>
#include <optional>

#include "part3.h"
#include "utils.h"

namespace
{
    using namespace std::string_view_literals;

    constexpr std::array vol_1 = std::to_array<const volume_definition>({
{ volume::P3V1, "toc.ncx"sv, "application/x-dtbncx+xml"sv, std::nullopt, false },
{ volume::P3V1, "Styles/stylesheet.css"sv, "text/css"sv, std::nullopt, false },
{ volume::P3V1, "Images/jnovelclubCMYK.png"sv, "image/png"sv, std::nullopt, false },
{ volume::P3V1, "Images/Bonus1.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V1, "Images/Bonus2.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V1, "Images/Characters1.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V1, "Images/Characters2.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V1, "Images/Cover.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V1, "Images/Extra1.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V1, "Images/FrontMatter1.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V1, "Images/FrontMatter2.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V1, "Images/Insert1.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V1, "Images/Insert2.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V1, "Images/Insert3.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V1, "Images/Insert4.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V1, "Images/Insert5.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V1, "Images/Insert6.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V1, "Images/Insert7.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V1, "Images/Insert8.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V1, "Images/Insert9.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V1, "Images/Manga1.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V1, "Images/Manga2.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V1, "Images/Extra2.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V1, "Images/Map.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V1, "Text/cover.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Cover"sv), true },
{ volume::P3V1, "Text/frontmatter1.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Color Illustrations"sv), true },
{ volume::P3V1, "Text/frontmatter2.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V1, "Text/map.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Map of Ehrenfest Duchy"sv), true },
{ volume::P3V1, "Text/characters1.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Characters"sv), true },
{ volume::P3V1, "Text/characters2.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V1, "Text/toc.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V1, "Text/prologue.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Prologue"sv), true },
{ volume::P3V1, "Text/chapter1.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Examination Results and the Noble’s Quarter"sv), true },
{ volume::P3V1, "Text/chapter2.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Preparing for the Baptism Ceremony"sv), true },
{ volume::P3V1, "Text/insert1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V1, "Text/chapter2_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V1, "Text/extra1.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Being My Little Sister’s Knight"sv), true },
{ volume::P3V1, "Text/chapter3.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("A Noble’s Baptism Ceremony"sv), true },
{ volume::P3V1, "Text/chapter4.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Adoption"sv), true },
{ volume::P3V1, "Text/insert2.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V1, "Text/chapter4_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V1, "Text/chapter5.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Inauguration Ceremony"sv), true },
{ volume::P3V1, "Text/chapter6.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Reunited at Last"sv), true },
{ volume::P3V1, "Text/insert3.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V1, "Text/chapter6_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V1, "Text/chapter7.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("How to Make Fluffy Bread"sv), true },
{ volume::P3V1, "Text/chapter8.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Starbind Ceremony in the Lower City"sv), true },
{ volume::P3V1, "Text/insert4.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V1, "Text/chapter9.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("The Archduke’s Castle"sv), true },
{ volume::P3V1, "Text/chapter10.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Starbind Ceremony in the Noble’s Quarter"sv), true },
{ volume::P3V1, "Text/chapter11.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("The Archduke and the Italian Restaurant"sv), true },
{ volume::P3V1, "Text/chapter12.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Making a Monastery"sv), true },
{ volume::P3V1, "Text/insert5.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V1, "Text/chapter12_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V1, "Text/extra2.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("One Stressed-Out Chef"sv), true },
{ volume::P3V1, "Text/chapter13.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("How to Gather Donations"sv), true },
{ volume::P3V1, "Text/insert6.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V1, "Text/chapter13_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V1, "Text/chapter14.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("My First Magic Training Regimen"sv), true },
{ volume::P3V1, "Text/chapter15.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Working Toward Wax Stencils"sv), true },
{ volume::P3V1, "Text/chapter16.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("An Illustration of Ferdinand"sv), true },
{ volume::P3V1, "Text/chapter17.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Johann and Zack"sv), true },
{ volume::P3V1, "Text/insert7.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V1, "Text/chapter17_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V1, "Text/chapter18.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Elvira and Lamprecht Attack"sv), true },
{ volume::P3V1, "Text/chapter19.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Finishing My Highbeast and the Wax Stencils"sv), true },
{ volume::P3V1, "Text/insert8.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V1, "Text/chapter19_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V1, "Text/chapter20.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("The Harspiel Concert"sv), true },
{ volume::P3V1, "Text/epilogue.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Epilogue"sv), true },
{ volume::P3V1, "Text/insert9.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V1, "Text/epilogue_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::FB2, "Text/side5.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("A Tea Party with My Older Sister"sv), true },
{ volume::FB2, "Styles/stylesheet.css"sv, "text/css"sv, std::nullopt, false },
{ volume::P3V1, "Text/afterword.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Afterword"sv), true },
{ volume::P3V1, "Text/manga1.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Coming Out of Nowhere Again, It’s the End of Volume Bonuses! by You Shiina"sv), true },
{ volume::P3V1, "Text/manga2.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V1, "Text/poll1.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("The 1st Ascendance of a Bookworm Character Poll!"sv), true },
{ volume::P3V1, "Text/poll2.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V1, "Text/bonus1.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Bonus High Resolution Illustrations"sv), true },
{ volume::P3V1, "Text/bonus2.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V1, "Text/signup.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("About J-Novel Club"sv), true },
{ volume::P3V1, "Text/copyright.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Copyright"sv), true },
    });


    constexpr std::array vol_2 = std::to_array<const volume_definition>({
{ volume::P3V2, "toc.ncx"sv, "application/x-dtbncx+xml"sv, std::nullopt, false },
{ volume::P3V2, "Styles/stylesheet.css"sv, "text/css"sv, std::nullopt, false },
{ volume::P3V2, "Images/jnovelclubCMYK.png"sv, "image/png"sv, std::nullopt, false },
{ volume::P3V2, "Images/Bonus1.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V2, "Images/Bonus2.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V2, "Images/Characters1.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V2, "Images/Characters2.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V2, "Images/Cover.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V2, "Images/FrontMatter1.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V2, "Images/FrontMatter2.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V2, "Images/Insert1.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V2, "Images/Insert2.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V2, "Images/Insert3.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V2, "Images/Insert4.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V2, "Images/Insert5.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V2, "Images/Insert6.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V2, "Images/Insert7.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V2, "Images/Insert8.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V2, "Images/Insert9.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V2, "Images/Manga1.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V2, "Images/Manga2.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V2, "Images/Characters3.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V2, "Images/Map.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V2, "Text/cover.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Cover"sv), true },
{ volume::P3V2, "Text/frontmatter1.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Color Illustrations"sv), true },
{ volume::P3V2, "Text/frontmatter2.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V2, "Text/map.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Map of Ehrenfest Duchy"sv), true },
{ volume::P3V2, "Text/characters1.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Characters"sv), true },
{ volume::P3V2, "Text/characters2.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V2, "Text/characters3.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V2, "Text/toc.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V2, "Text/prologue.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Prologue"sv), true },
{ volume::P3V2, "Text/insert1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V2, "Text/prologue_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V2, "Text/chapter1.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Discussing the Harvest Festival"sv), true },
{ volume::P3V2, "Text/chapter2.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Hasse’s Monastery"sv), true },
{ volume::P3V2, "Text/chapter3.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("The New Orphans"sv), true },
{ volume::P3V2, "Text/insert2.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V2, "Text/chapter3_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V2, "Text/chapter4.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("The Orphan’s Treatment and Investigating the City"sv), true },
{ volume::P3V2, "Text/chapter5.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("The Monastery’s Barrier"sv), true },
{ volume::P3V2, "Text/chapter6.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("A New Task and Winter Preparations"sv), true },
{ volume::P3V2, "Text/insert3.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V2, "Text/chapter6_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V2, "Text/chapter7.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Opening the Italian Restaurant"sv), true },
{ volume::P3V2, "Text/chapter8.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Discussing How to Improve Hasse"sv), true },
{ volume::P3V2, "Text/insert4.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V2, "Text/chapter8_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V2, "Text/chapter9.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Switching Places"sv), true },
{ volume::P3V2, "Text/insert5.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V2, "Text/chapter9_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V2, "Text/extra1.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Wilfried’s Day as the High Bishop"sv), true },
{ volume::P3V2, "Text/insert9.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V2, "Text/extra1_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V2, "Text/extra3.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Justus’s Grand Lower City Infiltration"sv), true },
{ volume::P3V2, "Text/chapter10.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Preparing for the Harvest Festival"sv), true },
{ volume::P3V2, "Text/chapter11.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Hasse’s Contract"sv), true },
{ volume::P3V2, "Text/chapter12.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Starting Merchant Activities"sv), true },
{ volume::P3V2, "Text/chapter13.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Hasse’s Harvest Festival"sv), true },
{ volume::P3V2, "Text/insert6.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V2, "Text/chapter14.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("The Harvest Festival"sv), true },
{ volume::P3V2, "Text/chapter15.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("The Night of Schutzaria"sv), true },
{ volume::P3V2, "Text/insert7.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V2, "Text/chapter15_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V2, "Text/chapter16.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Aftermath"sv), true },
{ volume::P3V2, "Text/insert8.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V2, "Text/chapter16_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V2, "Text/extra2.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Hasse’s Orphans"sv), true },
{ volume::P3V2, "Text/chapter17.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("My Winter Preparations"sv), true },
{ volume::P3V2, "Text/epilogue.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Epilogue"sv), true },
{ volume::P3V2, "Text/afterword.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Afterword"sv), true },
{ volume::P3V2, "Text/manga1.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("A Comfy Life with My Family by You Shiina"sv), true },
{ volume::P3V2, "Text/manga2.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V2, "Text/bonus1.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Bonus High Resolution Illustrations"sv), true },
{ volume::P3V2, "Text/bonus2.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V2, "Text/signup.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("About J-Novel Club"sv), true },
{ volume::P3V2, "Text/copyright.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Copyright"sv), true },
        });


constexpr std::array vol_3 = std::to_array<const volume_definition>({
{ volume::P3V3, "toc.ncx"sv, "application/x-dtbncx+xml"sv, std::nullopt, false },
{ volume::P3V3, "Styles/stylesheet.css"sv, "text/css"sv, std::nullopt, false },
{ volume::P3V3, "Images/jnovelclubCMYK.png"sv, "image/png"sv, std::nullopt, false },
{ volume::P3V3, "Images/Bonus1.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V3, "Images/Bonus2.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V3, "Images/Characters1.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V3, "Images/Characters2.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V3, "Images/Cover.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V3, "Images/FrontMatter1.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V3, "Images/FrontMatter2.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V3, "Images/Insert1.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V3, "Images/Insert2.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V3, "Images/Insert3.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V3, "Images/Insert4.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V3, "Images/Insert5.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V3, "Images/Insert6.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V3, "Images/Insert7.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V3, "Images/Insert8.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V3, "Images/Insert9.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V3, "Images/Manga1.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V3, "Images/Manga2.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V3, "Images/Map.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V3, "Images/Characters3.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V3, "Images/Insert10.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V3, "Text/cover.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Cover"sv), true },
{ volume::P3V3, "Text/frontmatter1.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Color Illustrations"sv), true },
{ volume::P3V3, "Text/frontmatter2.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V3, "Text/map.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Map of Ehrenfest Duchy"sv), true },
{ volume::P3V3, "Text/characters1.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Characters"sv), true },
{ volume::P3V3, "Text/characters2.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V3, "Text/characters3.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V3, "Text/toc.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V3, "Text/prologue.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Prologue"sv), true },
{ volume::P3V3, "Text/chapter1.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Ingo and Improving the Printing Press"sv), true },
{ volume::P3V3, "Text/chapter2.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("The Gathering of the Gutenbergs"sv), true },
{ volume::P3V3, "Text/insert1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V3, "Text/chapter2_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V3, "Text/extra2.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("The High Bishop’s Exclusive Business"sv), true },
{ volume::P3V3, "Text/chapter3.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("The Start of Winter Socializing"sv), true },
{ volume::P3V3, "Text/chapter4.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("The Baptism Ceremony and Our Winter Debut"sv), true },
{ volume::P3V3, "Text/insert2.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V3, "Text/chapter4_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V3, "Text/chapter5.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("A Class for Kids"sv), true },
{ volume::P3V3, "Text/insert3.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V3, "Text/chapter5_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V3, "Text/chapter6.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("A Tea Party"sv), true },
{ volume::P3V3, "Text/chapter7.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("The Dedication Ritual (Take Two)"sv), true },
{ volume::P3V3, "Text/extra1.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Winter Debut and the Playroom"sv), true },
{ volume::P3V3, "Text/chapter8.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Gathering the Winter Ingredient"sv), true },
{ volume::P3V3, "Text/chapter9.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Fighting the Schnesturm"sv), true },
{ volume::P3V3, "Text/insert4.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V3, "Text/chapter9_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V3, "Text/chapter10.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("To the End of Winter"sv), true },
{ volume::P3V3, "Text/chapter11.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Selling the Materials"sv), true },
{ volume::P3V3, "Text/chapter12.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Angelica and the Coming of Spring"sv), true },
{ volume::P3V3, "Text/insert5.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V3, "Text/chapter12_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V3, "Text/chapter13.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Upcoming Spring Prayer"sv), true },
{ volume::P3V3, "Text/insert6.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V3, "Text/chapter13_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V3, "Text/chapter14.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Hasse’s Punishment"sv), true },
{ volume::P3V3, "Text/chapter15.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("The Door of Judgment"sv), true },
{ volume::P3V3, "Text/chapter16.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("The Execution"sv), true },
{ volume::P3V3, "Text/insert7.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V3, "Text/chapter16_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V3, "Text/chapter17.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("The Spring Ingredient and Discussing Spring Prayer"sv), true },
{ volume::P3V3, "Text/chapter18.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("The Goddesses’ Bath"sv), true },
{ volume::P3V3, "Text/insert8.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V3, "Text/chapter18_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V3, "Text/chapter19.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("The Night of Flutrane"sv), true },
{ volume::P3V3, "Text/chapter20.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("The End of Spring Prayer"sv), true },
{ volume::P3V3, "Text/insert9.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V3, "Text/chapter20_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V3, "Text/epilogue.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Epilogue"sv), true },
{ volume::P3V3, "Text/afterword.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Afterword"sv), true },
{ volume::P3V3, "Text/manga1.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("A Comfy Life with My Family by You Shiina"sv), true },
{ volume::P3V3, "Text/manga2.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V3, "Text/insert10.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Jureve Ingredients"sv), true },
{ volume::P3V3, "Text/bonus1.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Bonus High Resolution Illustrations"sv), true },
{ volume::P3V3, "Text/bonus2.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V3, "Text/signup.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("About J-Novel Club"sv), true },
{ volume::P3V3, "Text/copyright.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Copyright"sv), true },

        });


constexpr std::array vol_4 = std::to_array<const volume_definition>({
{ volume::P3V4, "toc.ncx"sv, "application/x-dtbncx+xml"sv, std::nullopt, false },
{ volume::P3V4, "Styles/stylesheet.css"sv, "text/css"sv, std::nullopt, false },
{ volume::P3V4, "Images/jnovelclubCMYK.png"sv, "image/png"sv, std::nullopt, false },
{ volume::P3V4, "Images/Bonus1.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V4, "Images/Bonus2.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V4, "Images/Characters1.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V4, "Images/Characters2.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V4, "Images/Characters3.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V4, "Images/FrontMatter1.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V4, "Images/FrontMatter2.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V4, "Images/Insert1.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V4, "Images/Insert2.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V4, "Images/Insert3.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V4, "Images/Insert4.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V4, "Images/Insert5.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V4, "Images/Insert6.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V4, "Images/Insert7.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V4, "Images/Insert8.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V4, "Images/Insert9.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V4, "Images/Manga1.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V4, "Images/Manga2.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V4, "Images/Map.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V4, "Images/Cover.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V4, "Images/Insert10.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V4, "Text/cover.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Cover"sv), true },
{ volume::P3V4, "Text/frontmatter1.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Color Illustrations"sv), true },
{ volume::P3V4, "Text/frontmatter2.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V4, "Text/map.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Map of Ehrenfest Duchy"sv), true },
{ volume::P3V4, "Text/characters1.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Characters"sv), true },
{ volume::P3V4, "Text/characters2.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V4, "Text/characters3.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V4, "Text/toc.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V4, "Text/prologue.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Prologue"sv), true },
{ volume::P3V4, "Text/chapter1.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("A New Dress"sv), true },
{ volume::P3V4, "Text/chapter2.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("The New Printing Press’s Trial Run"sv), true },
{ volume::P3V4, "Text/insert1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V4, "Text/chapter2_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V4, "Text/chapter3.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Benno’s Request"sv), true },
{ volume::P3V4, "Text/chapter4.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Staying Home During the Archduke Conference"sv), true },
{ volume::P3V4, "Text/chapter5.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Payment and Unveiling the Dress"sv), true },
{ volume::P3V4, "Text/chapter6.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Angelica’s Manablade"sv), true },
{ volume::P3V4, "Text/insert2.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V4, "Text/chapter6_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V4, "Text/chapter7.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Let’s Print More Stuff"sv), true },
{ volume::P3V4, "Text/chapter8.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Meeting with the Plantin Company"sv), true },
{ volume::P3V4, "Text/insert3.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V4, "Text/chapter8_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V4, "Text/chapter9.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("The Archducal Couple Returns"sv), true },
{ volume::P3V4, "Text/chapter10.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("The Dress Debut and Ferdinand’s Return"sv), true },
{ volume::P3V4, "Text/insert4.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V4, "Text/chapter10_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V4, "Text/chapter11.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Lunch Meeting and Business Day"sv), true },
{ volume::P3V4, "Text/chapter12.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Heading to Illgner"sv), true },
{ volume::P3V4, "Text/chapter13.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Illgner’s Brigitte"sv), true },
{ volume::P3V4, "Text/insert5.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V4, "Text/chapter13_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V4, "Text/chapter21.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Damuel’s Proposal"sv), true },
{ volume::P3V4, "Text/insert9.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V4, "Text/chapter21_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V4, "Text/chapter14.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Mount Lohenberg"sv), true },
{ volume::P3V4, "Text/chapter15.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("The Riesefalke Egg"sv), true },
{ volume::P3V4, "Text/insert6.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V4, "Text/chapter15_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V4, "Text/chapter16.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Hand Pumps"sv), true },
{ volume::P3V4, "Text/insert7.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V4, "Text/chapter16_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V4, "Text/chapter17.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Georgine’s Visit"sv), true },
{ volume::P3V4, "Text/insert8.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V4, "Text/chapter17_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V4, "Text/chapter18.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Dirk’s Mana and Submission Contract"sv), true },
{ volume::P3V4, "Text/chapter22.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Staying in Illgner"sv), true },
{ volume::P3V4, "Text/chapter19.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Georgine Departs"sv), true },
{ volume::P3V4, "Text/chapter20.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Tea Party"sv), true },
{ volume::P3V4, "Text/epilogue.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Epilogue"sv), true },
{ volume::P3V4, "Text/afterword.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Afterword"sv), true },
{ volume::P3V4, "Text/manga1.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("A Comfy Life with My Family by You Shiina"sv), true },
{ volume::P3V4, "Text/manga2.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V4, "Text/insert10.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Jureve Ingredients"sv), true },
{ volume::P3V4, "Text/bonus1.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Bonus High Resolution Illustrations"sv), true },
{ volume::P3V4, "Text/bonus2.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V4, "Text/signup.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("About J-Novel Club"sv), true },
{ volume::P3V4, "Text/copyright.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Copyright"sv), true },
        });

constexpr std::array vol_5 = std::to_array<const volume_definition>({
{ volume::P3V5, "toc.ncx"sv, "application/x-dtbncx+xml"sv, std::nullopt, false },
{ volume::P3V5, "Styles/stylesheet.css"sv, "text/css"sv, std::nullopt, false },
{ volume::P3V5, "Images/jnovelclubCMYK.png"sv, "image/png"sv, std::nullopt, false },
{ volume::P3V5, "Images/Map.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V5, "Images/Bonus1.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V5, "Images/Bonus2.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V5, "Images/Characters1.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V5, "Images/Characters2.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V5, "Images/Characters3.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V5, "Images/Cover.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V5, "Images/FrontMatter1.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V5, "Images/FrontMatter2.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V5, "Images/Insert1.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V5, "Images/Insert2.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V5, "Images/Insert3.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V5, "Images/Insert4.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V5, "Images/Insert5.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V5, "Images/Insert6.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V5, "Images/Insert7.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V5, "Images/Insert8.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V5, "Images/Insert9.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V5, "Images/Insert10.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V5, "Images/Manga2.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V5, "Images/Manga1.jpg"sv, "image/jpeg"sv, std::nullopt, false },
{ volume::P3V5, "Text/cover.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Cover"sv), true },
{ volume::P3V5, "Text/frontmatter1.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Color Illustrations"sv), true },
{ volume::P3V5, "Text/frontmatter2.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V5, "Text/map.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Map of Ehrenfest Duchy"sv), true },
{ volume::P3V5, "Text/characters1.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Characters"sv), true },
{ volume::P3V5, "Text/characters2.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V5, "Text/characters3.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V5, "Text/toc.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V5, "Text/prologue.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Prologue"sv), true },
{ volume::P3V5, "Text/insert1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V5, "Text/prologue_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V5, "Text/chapter1.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("The New Orphans and Operation Grimm"sv), true },
{ volume::P3V5, "Text/chapter2.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Hasse and the Gray Priests"sv), true },
{ volume::P3V5, "Text/chapter3.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Ruelle Gathering (Take Two)"sv), true },
{ volume::P3V5, "Text/chapter4.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Damuel’s Growth"sv), true },
{ volume::P3V5, "Text/insert2.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V5, "Text/chapter4_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V5, "Text/chapter5.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Conditions for Compressing Mana"sv), true },
{ volume::P3V5, "Text/chapter6.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Illgner’s Harvest Festival"sv), true },
{ volume::P3V5, "Text/chapter7.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("My First-Ever Little Sister"sv), true },
{ volume::P3V5, "Text/insert3.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V5, "Text/chapter7_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V5, "Text/chapter8.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Wilfried’s Actions"sv), true },
{ volume::P3V5, "Text/insert4.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V5, "Text/chapter8_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V5, "Text/chapter9.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Wilfried’s Punishment"sv), true },
{ volume::FB2, "Text/side6.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Feelings of Panic"sv), true },
{ volume::FB2, "Styles/stylesheet.css"sv, "text/css"sv, std::nullopt, false },
{ volume::P3V5, "Text/chapter10.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("The Jureve and Mana Compression"sv), true },
{ volume::P3V5, "Text/chapter11.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Charlotte’s Baptism Ceremony"sv), true },
{ volume::P3V5, "Text/chapter12.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Kidnapped Daughter"sv), true },
{ volume::P3V5, "Text/chapter13.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Rescue"sv), true },
{ volume::P3V5, "Text/insert5.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V5, "Text/chapter13_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V5, "Text/chapter14.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("And So, the Future"sv), true },
{ volume::P3V5, "Text/chapter15.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Grandfather on the Day of the Baptism"sv), true },
{ volume::P3V5, "Text/chapter16.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("In Place of My Older Sister"sv), true },
{ volume::P3V5, "Text/insert6.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V5, "Text/chapter16_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V5, "Text/chapter17.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Two Marriages"sv), true },
{ volume::P3V5, "Text/chapter20.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("The Laynoble Guard Knight"sv), true },
{ volume::P3V5, "Text/chapter21.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("One Handful of a Chef"sv), true },
{ volume::P3V5, "Text/chapter18.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("No Rest for Us"sv), true },
{ volume::P3V5, "Text/insert7.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V5, "Text/chapter18_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V5, "Text/insert8.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V5, "Text/chapter18_2.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V5, "Text/chapter19.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Meanwhile at the Temple"sv), true },
{ volume::P3V5, "Text/insert9.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V5, "Text/chapter19_1.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V5, "Text/epilogue.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Epilogue"sv), true },
{ volume::P3V5, "Text/afterword.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Afterword"sv), true },
{ volume::P3V5, "Text/manga1.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("A Comfy Life with My Family by You Shiina"sv), true },
{ volume::P3V5, "Text/manga2.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V5, "Text/insert10.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Jureve Ingredients"sv), true },
{ volume::P3V5, "Text/bonus1.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Bonus High Resolution Illustrations"sv), true },
{ volume::P3V5, "Text/bonus2.xhtml"sv, "application/xhtml+xml"sv, std::nullopt, true },
{ volume::P3V5, "Text/signup.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("About J-Novel Club"sv), true },
{ volume::P3V5, "Text/copyright.xhtml"sv, "application/xhtml+xml"sv, std::make_optional<std::string_view>("Copyright"sv), true },
        });

    constexpr std::array _part_3_list = std::to_array<std::span<const volume_definition>>({
        std::span(vol_1), std::span(vol_2), std::span(vol_3), std::span(vol_4), std::span(vol_5)
    });

    consteval auto _get_part3_view()
    {
        constexpr std::ranges::join_view l{_part_3_list};
        constexpr auto sz = std::distance(l.begin(), l.end());
        std::vector<volume_definition> v(l.begin(),
                                         l.end());
        return utils::vec_to_arr<sz>(v);
    }

    constexpr std::array _part_3_view = _get_part3_view();

    const std::vector<volume_definition> _part_3 = utils::make_omnibus_def(_part_3_view, utils::calc_reservation(_part_3_list));
}


namespace part_3
{
    using namespace std::string_view_literals;

    std::span<const volume_definition>
    get_vol_1()
    {
        return std::span<const volume_definition>(vol_1);
    }

    std::span<const volume_definition>
    get_vol_2()
    {
        return std::span<const volume_definition>(vol_2);
    }

    std::span<const volume_definition>
    get_vol_3()
    {
        return std::span<const volume_definition>(vol_3);
    }

    std::span<const volume_definition>
    get_vol_4()
    {
        return std::span<const volume_definition>(vol_4);
    }

    std::span<const volume_definition>
    get_vol_5()
    {
        return std::span<const volume_definition>(vol_5);
    }


    std::span<const volume_definition>
    get_part_3()
    {
        return std::span<const volume_definition>(_part_3);
    }

    size_t
    get_reservation()
    {
        return _part_3.size();
    }
}
